name: Test
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.x
          run_install: |
            - recursive: false
      - name: Run Test
        run: pnpm test
        env:
          CI: true
